// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"jxChainWebSvc/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: JxChainDataGetHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/put",
				Handler: JxChainDataPutHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: JxChainDataDeleteHandler(serverCtx),
			},
		},
	)
}
