// Code generated by goctl. DO NOT EDIT.
package types

type QueryData struct {
	AlertorID string `json:"alertorID"`
}

type DeleteData struct {
	AlertorID string `json:"alertorID"`
}

type OnChainDataPut struct {
	AlertorID      string `json:"alertorID"`        //传感器ID
	AlertTime      string `json:"alertTime"`      //发出警报的时间
	HouseNumber    string `json:"houseNumber"`    //住宅编号或者房建号
	HouseOwnerName string `json:"houseOwnerName"` //住户的名字
}

type OnChainStatus struct {
	Message string `json:"message"`
}
